### ISSUE TITLE
This is not a issue concerning bootstrap-cfwheels but

### ISSUE THREAD

**Issue by devalnor** [liquifusion/bootstrap-cfwheels#2]
Just for your info it's hard to contact you...
Your Twitter account is down and your LinkedIn closed...

I mean theses from here: http://cfwheels.org/user/profile/1

By the way, I had also working on a same kind of plugins so I will follow it :)

Regard.

**Comment by chrisdpeters** [comment]
Thanks for the heads up on the profile. Got the Twitter handle fixed.

Do you have the URL for your version of the plugin?
